[2023-05-04T11:09:33.714+0000] {processor.py:153} INFO - Started process (PID=23127) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:09:33.716+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:09:33.718+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:09:33.718+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:09:33.750+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:09:33.746+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:09:33.755+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:09:33.798+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.091 seconds
[2023-05-04T11:10:04.326+0000] {processor.py:153} INFO - Started process (PID=23169) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:10:04.333+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:10:04.338+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:10:04.338+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:10:04.371+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:10:04.368+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:10:04.372+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:10:04.407+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.085 seconds
[2023-05-04T11:10:34.965+0000] {processor.py:153} INFO - Started process (PID=23211) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:10:34.967+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:10:34.970+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:10:34.970+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:10:34.999+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:10:34.997+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:10:35.001+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:10:35.028+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.068 seconds
[2023-05-04T11:11:05.600+0000] {processor.py:153} INFO - Started process (PID=23258) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:11:05.603+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:11:05.605+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:11:05.605+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:11:05.632+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:11:05.630+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:11:05.634+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:11:05.658+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.063 seconds
[2023-05-04T11:11:36.497+0000] {processor.py:153} INFO - Started process (PID=23300) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:11:36.499+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:11:36.501+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:11:36.501+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:11:36.530+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:11:36.527+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:11:36.531+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:11:36.559+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.067 seconds
[2023-05-04T11:12:07.331+0000] {processor.py:153} INFO - Started process (PID=23348) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:12:07.334+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:12:07.336+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:12:07.335+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:12:07.364+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:12:07.361+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:12:07.366+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:12:07.393+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.067 seconds
[2023-05-04T11:12:37.474+0000] {processor.py:153} INFO - Started process (PID=23392) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:12:37.478+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:12:37.480+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:12:37.480+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:12:37.508+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:12:37.505+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:12:37.509+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:12:37.536+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.071 seconds
[2023-05-04T11:13:08.243+0000] {processor.py:153} INFO - Started process (PID=23442) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:13:08.245+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:13:08.247+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:13:08.247+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:13:08.273+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:13:08.271+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:13:08.275+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:13:08.301+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.064 seconds
[2023-05-04T11:13:39.050+0000] {processor.py:153} INFO - Started process (PID=23484) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:13:39.054+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:13:39.056+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:13:39.056+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:13:39.109+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:13:39.105+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:13:39.111+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:13:39.161+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.121 seconds
[2023-05-04T11:14:09.949+0000] {processor.py:153} INFO - Started process (PID=23738) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:14:09.952+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:14:09.955+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:14:09.955+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:14:09.985+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:14:09.982+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:14:09.988+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:14:10.021+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.077 seconds
[2023-05-04T11:14:40.504+0000] {processor.py:153} INFO - Started process (PID=24064) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:14:40.509+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:14:40.516+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:14:40.516+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:14:40.613+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:14:40.601+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:14:40.620+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:14:40.702+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.207 seconds
[2023-05-04T11:15:10.879+0000] {processor.py:153} INFO - Started process (PID=24347) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:15:10.881+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:15:10.883+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:15:10.883+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:15:10.911+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:15:10.908+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:15:10.913+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:15:10.939+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.066 seconds
[2023-05-04T11:15:41.170+0000] {processor.py:153} INFO - Started process (PID=24632) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:15:41.172+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:15:41.178+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:15:41.178+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:15:41.224+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:15:41.220+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:15:41.227+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:15:41.265+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.101 seconds
[2023-05-04T11:16:11.381+0000] {processor.py:153} INFO - Started process (PID=24945) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:16:11.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:16:11.402+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:16:11.401+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:16:11.566+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:16:11.559+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:16:11.574+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:16:11.637+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.269 seconds
[2023-05-04T11:16:41.765+0000] {processor.py:153} INFO - Started process (PID=25202) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:16:41.768+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:16:41.770+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:16:41.769+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:16:41.796+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:16:41.793+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:16:41.798+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:16:41.822+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.064 seconds
[2023-05-04T11:17:11.971+0000] {processor.py:153} INFO - Started process (PID=25532) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:17:11.974+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:17:11.976+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:17:11.976+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:17:12.003+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:17:12.001+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:17:12.005+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:17:12.028+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.063 seconds
[2023-05-04T11:17:42.725+0000] {processor.py:153} INFO - Started process (PID=25861) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:17:42.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:17:42.729+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:17:42.729+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:17:42.757+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:17:42.755+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:17:42.759+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:17:42.786+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.066 seconds
[2023-05-04T11:18:13.753+0000] {processor.py:153} INFO - Started process (PID=26193) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:18:13.755+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:18:13.757+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:18:13.757+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:18:13.784+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:18:13.782+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:18:13.786+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:18:13.809+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.062 seconds
[2023-05-04T11:18:44.357+0000] {processor.py:153} INFO - Started process (PID=26521) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:18:44.359+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:18:44.361+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:18:44.361+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:18:44.393+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:18:44.390+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:18:44.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:18:44.421+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.070 seconds
[2023-05-04T11:19:14.545+0000] {processor.py:153} INFO - Started process (PID=26818) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:19:14.553+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:19:14.564+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:19:14.563+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:19:14.626+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:19:14.613+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:19:14.629+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:19:14.718+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.192 seconds
[2023-05-04T11:19:45.126+0000] {processor.py:153} INFO - Started process (PID=27161) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:19:45.134+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:19:45.141+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:19:45.139+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:19:45.276+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:19:45.266+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:19:45.279+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:19:45.359+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.241 seconds
[2023-05-04T11:20:15.541+0000] {processor.py:153} INFO - Started process (PID=27479) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:20:15.554+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:20:15.557+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:20:15.557+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:20:15.619+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:20:15.611+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:20:15.622+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:20:15.718+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.203 seconds
[2023-05-04T11:20:45.833+0000] {processor.py:153} INFO - Started process (PID=27784) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:20:45.836+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:20:45.839+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:20:45.838+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:20:45.888+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:20:45.880+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:20:45.895+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:20:45.926+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.099 seconds
[2023-05-04T11:21:16.542+0000] {processor.py:153} INFO - Started process (PID=28097) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:21:16.555+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:21:16.558+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:21:16.558+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:21:16.712+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:21:16.705+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:21:16.714+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:21:16.807+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.285 seconds
[2023-05-04T11:21:47.773+0000] {processor.py:153} INFO - Started process (PID=28430) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:21:47.778+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:21:47.784+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:21:47.783+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:21:47.834+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:21:47.830+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:21:47.842+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:21:47.906+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.155 seconds
[2023-05-04T11:22:18.722+0000] {processor.py:153} INFO - Started process (PID=28781) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:22:18.732+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:22:18.740+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:22:18.740+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:22:18.880+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:22:18.852+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:22:18.888+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:22:18.941+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.245 seconds
[2023-05-04T11:22:49.089+0000] {processor.py:153} INFO - Started process (PID=29091) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:22:49.092+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:22:49.107+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:22:49.107+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:22:49.157+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:22:49.150+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:22:49.162+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:22:49.215+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.131 seconds
[2023-05-04T11:23:20.016+0000] {processor.py:153} INFO - Started process (PID=29398) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:23:20.023+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:23:20.028+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:23:20.027+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:23:20.103+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:23:20.098+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:23:20.106+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:23:20.185+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.185 seconds
[2023-05-04T11:23:50.620+0000] {processor.py:153} INFO - Started process (PID=29687) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:23:50.623+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:23:50.632+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:23:50.632+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:23:50.697+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:23:50.692+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:23:50.703+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:23:50.756+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.148 seconds
[2023-05-04T11:24:21.514+0000] {processor.py:153} INFO - Started process (PID=29965) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:24:21.526+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:24:21.529+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:24:21.529+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:24:21.784+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:24:21.768+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:24:21.793+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:24:21.913+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.414 seconds
[2023-05-04T11:24:52.080+0000] {processor.py:153} INFO - Started process (PID=30264) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:24:52.083+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:24:52.086+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:24:52.085+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:24:52.121+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:24:52.118+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:24:52.123+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:24:52.159+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.088 seconds
[2023-05-04T11:25:22.354+0000] {processor.py:153} INFO - Started process (PID=30586) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:25:22.357+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:25:22.360+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:25:22.359+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:25:22.447+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:25:22.431+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:25:22.452+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:25:22.542+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.195 seconds
[2023-05-04T11:25:52.877+0000] {processor.py:153} INFO - Started process (PID=30904) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:25:52.882+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:25:52.885+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:25:52.885+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:25:52.983+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:25:52.969+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:25:52.986+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:25:53.028+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.160 seconds
[2023-05-04T11:26:23.741+0000] {processor.py:153} INFO - Started process (PID=31160) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:26:23.746+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:26:23.752+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:26:23.752+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:26:23.856+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:26:23.849+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:26:23.858+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:26:23.946+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.212 seconds
[2023-05-04T11:26:54.140+0000] {processor.py:153} INFO - Started process (PID=31450) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:26:54.142+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:26:54.145+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:26:54.144+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:26:54.172+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:26:54.170+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:26:54.174+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:26:54.202+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.067 seconds
[2023-05-04T11:27:24.853+0000] {processor.py:153} INFO - Started process (PID=31797) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:27:24.857+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:27:24.860+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:27:24.860+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:27:25.019+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:27:25.010+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:27:25.022+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:27:25.120+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.300 seconds
[2023-05-04T11:27:55.302+0000] {processor.py:153} INFO - Started process (PID=32076) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:27:55.312+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:27:55.320+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:27:55.319+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:27:55.398+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:27:55.393+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:27:55.401+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:27:55.438+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.144 seconds
[2023-05-04T11:28:26.256+0000] {processor.py:153} INFO - Started process (PID=32360) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:28:26.261+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:28:26.265+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:28:26.264+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:28:26.338+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:28:26.328+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:28:26.341+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:28:26.395+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.148 seconds
[2023-05-04T11:28:57.416+0000] {processor.py:153} INFO - Started process (PID=32662) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:28:57.419+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:28:57.421+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:28:57.421+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:28:57.571+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:28:57.555+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:28:57.575+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:28:57.680+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.269 seconds
[2023-05-04T11:29:27.975+0000] {processor.py:153} INFO - Started process (PID=32949) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:29:27.979+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:29:27.981+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:29:27.981+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:29:28.025+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:29:28.021+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:29:28.029+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:29:28.060+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.092 seconds
[2023-05-04T11:29:58.655+0000] {processor.py:153} INFO - Started process (PID=33252) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:29:58.659+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:29:58.661+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:29:58.661+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:29:58.700+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:29:58.697+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:29:58.704+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:29:58.740+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.093 seconds
[2023-05-04T11:30:29.556+0000] {processor.py:153} INFO - Started process (PID=33529) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:30:29.559+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:30:29.562+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:30:29.562+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:30:29.644+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:30:29.633+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:30:29.646+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:30:29.725+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.190 seconds
[2023-05-04T11:31:00.625+0000] {processor.py:153} INFO - Started process (PID=33791) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:31:00.629+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:31:00.632+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:31:00.632+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:31:00.706+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:31:00.692+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:31:00.710+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:31:00.780+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.173 seconds
[2023-05-04T11:31:30.949+0000] {processor.py:153} INFO - Started process (PID=34081) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:31:30.952+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:31:30.954+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:31:30.954+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:31:30.982+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:31:30.979+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:31:30.983+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:31:31.013+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.069 seconds
[2023-05-04T11:32:01.146+0000] {processor.py:153} INFO - Started process (PID=34358) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:32:01.151+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:32:01.155+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:32:01.154+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:32:01.208+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:32:01.203+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:32:01.210+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:32:01.253+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.123 seconds
[2023-05-04T11:32:31.369+0000] {processor.py:153} INFO - Started process (PID=34630) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:32:31.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:32:31.380+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:32:31.378+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:32:31.460+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:32:31.457+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:32:31.472+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:32:31.536+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.189 seconds
[2023-05-04T11:33:02.005+0000] {processor.py:153} INFO - Started process (PID=34901) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:33:02.010+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:33:02.012+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:33:02.012+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:33:02.071+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:33:02.056+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:33:02.076+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:33:02.132+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.137 seconds
[2023-05-04T11:33:33.119+0000] {processor.py:153} INFO - Started process (PID=35188) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:33:33.123+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:33:33.133+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:33:33.131+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:33:33.199+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:33:33.188+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:33:33.203+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:33:33.305+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.222 seconds
[2023-05-04T11:34:04.106+0000] {processor.py:153} INFO - Started process (PID=35459) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:34:04.110+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:34:04.112+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:34:04.112+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:34:04.156+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:34:04.152+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:34:04.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:34:04.213+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.117 seconds
[2023-05-04T11:34:34.475+0000] {processor.py:153} INFO - Started process (PID=35773) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:34:34.477+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:34:34.478+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:34:34.478+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:34:34.505+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:34:34.502+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:34:34.507+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:34:34.540+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.071 seconds
[2023-05-04T11:35:05.221+0000] {processor.py:153} INFO - Started process (PID=36062) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:35:05.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:35:05.232+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:35:05.231+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:35:05.289+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:35:05.276+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:35:05.293+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:35:05.340+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.127 seconds
[2023-05-04T11:35:35.921+0000] {processor.py:153} INFO - Started process (PID=36349) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:35:35.926+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:35:35.944+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:35:35.944+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:35:36.091+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:35:36.074+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:35:36.104+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:35:36.199+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.289 seconds
[2023-05-04T11:36:06.919+0000] {processor.py:153} INFO - Started process (PID=36613) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:36:06.922+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:36:06.925+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:36:06.925+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:36:06.985+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:36:06.977+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:36:06.990+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:36:07.034+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.122 seconds
[2023-05-04T11:36:37.285+0000] {processor.py:153} INFO - Started process (PID=36904) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:36:37.289+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:36:37.298+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:36:37.292+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:36:37.349+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:36:37.341+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:36:37.351+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:36:37.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.113 seconds
[2023-05-04T11:37:07.594+0000] {processor.py:153} INFO - Started process (PID=37183) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:37:07.596+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:37:07.598+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:37:07.597+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:37:07.620+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:37:07.618+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:37:07.622+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:37:07.645+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.056 seconds
[2023-05-04T11:37:38.425+0000] {processor.py:153} INFO - Started process (PID=37226) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:37:38.435+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:37:38.438+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:37:38.438+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:37:38.473+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:37:38.469+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:37:38.475+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:37:38.522+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.112 seconds
[2023-05-04T11:38:08.667+0000] {processor.py:153} INFO - Started process (PID=37331) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:38:08.669+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:38:08.671+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:38:08.670+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:38:08.694+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:38:08.692+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:38:08.696+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:38:08.721+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.059 seconds
[2023-05-04T11:38:39.482+0000] {processor.py:153} INFO - Started process (PID=37436) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:38:39.485+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:38:39.488+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:38:39.487+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:38:39.524+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:38:39.521+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:38:39.526+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:38:39.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.079 seconds
[2023-05-04T11:39:10.167+0000] {processor.py:153} INFO - Started process (PID=37450) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:39:10.169+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:39:10.172+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:39:10.172+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:39:10.201+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:39:10.198+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:39:10.203+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:39:10.230+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.069 seconds
[2023-05-04T11:39:40.982+0000] {processor.py:153} INFO - Started process (PID=37464) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:39:40.986+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:39:41.008+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:39:41.008+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:39:41.041+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:39:41.037+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:39:41.042+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:39:41.088+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.112 seconds
[2023-05-04T11:40:11.815+0000] {processor.py:153} INFO - Started process (PID=37478) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:40:11.819+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:40:11.821+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:40:11.821+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:40:11.849+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:40:11.847+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:40:11.852+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:40:11.879+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.070 seconds
[2023-05-04T11:40:42.509+0000] {processor.py:153} INFO - Started process (PID=37492) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:40:42.511+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:40:42.513+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:40:42.513+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:40:42.542+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:40:42.540+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:40:42.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:40:42.570+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.067 seconds
[2023-05-04T11:41:13.256+0000] {processor.py:153} INFO - Started process (PID=37506) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:41:13.259+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:41:13.261+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:41:13.261+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:41:13.291+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:41:13.288+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:41:13.293+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:41:13.317+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.067 seconds
[2023-05-04T11:41:43.898+0000] {processor.py:153} INFO - Started process (PID=37520) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:41:43.901+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:41:43.903+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:41:43.903+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:41:43.930+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:41:43.928+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:41:43.933+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:41:43.958+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.065 seconds
[2023-05-04T11:42:14.547+0000] {processor.py:153} INFO - Started process (PID=37534) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:42:14.550+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:42:14.551+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:42:14.551+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:42:14.577+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:42:14.574+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:42:14.578+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:42:14.603+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.061 seconds
[2023-05-04T11:42:45.179+0000] {processor.py:153} INFO - Started process (PID=37548) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:42:45.182+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:42:45.184+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:42:45.184+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:42:45.209+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:42:45.207+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:42:45.210+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:42:45.231+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.057 seconds
[2023-05-04T11:43:15.778+0000] {processor.py:153} INFO - Started process (PID=37562) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:43:15.780+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:43:15.782+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:43:15.782+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:43:15.806+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:43:15.804+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:43:15.807+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:43:15.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.058 seconds
[2023-05-04T11:43:46.377+0000] {processor.py:153} INFO - Started process (PID=37576) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:43:46.381+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:43:46.383+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:43:46.383+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:43:46.408+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:43:46.406+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:43:46.410+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:43:46.434+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.062 seconds
[2023-05-04T11:44:16.976+0000] {processor.py:153} INFO - Started process (PID=37590) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:44:16.978+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:44:16.980+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:44:16.980+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:44:17.008+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:44:17.005+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:44:17.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:44:17.033+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.063 seconds
[2023-05-04T11:44:47.627+0000] {processor.py:153} INFO - Started process (PID=37604) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:44:47.630+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:44:47.632+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:44:47.632+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:44:47.660+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:44:47.657+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:44:47.661+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:44:47.686+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.065 seconds
[2023-05-04T11:45:18.219+0000] {processor.py:153} INFO - Started process (PID=37618) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:45:18.222+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:45:18.224+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:45:18.224+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:45:18.249+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:45:18.247+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:45:18.251+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:45:18.273+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.059 seconds
[2023-05-04T11:45:48.832+0000] {processor.py:153} INFO - Started process (PID=37632) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:45:48.835+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:45:48.837+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:45:48.836+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:45:48.861+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:45:48.859+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:45:48.862+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:45:48.883+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.057 seconds
[2023-05-04T11:46:19.436+0000] {processor.py:153} INFO - Started process (PID=37646) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:46:19.438+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:46:19.441+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:46:19.440+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:46:19.470+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:46:19.468+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:46:19.472+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:46:19.495+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.066 seconds
[2023-05-04T11:46:50.060+0000] {processor.py:153} INFO - Started process (PID=37660) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:46:50.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:46:50.064+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:46:50.064+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:46:50.086+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:46:50.084+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:46:50.087+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:46:50.109+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.054 seconds
[2023-05-04T11:47:20.658+0000] {processor.py:153} INFO - Started process (PID=37674) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:47:20.661+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:47:20.663+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:47:20.662+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:47:20.686+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:47:20.684+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:47:20.688+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:47:20.709+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.058 seconds
[2023-05-04T11:47:51.258+0000] {processor.py:153} INFO - Started process (PID=37688) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:47:51.260+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:47:51.261+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:47:51.261+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:47:51.284+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:47:51.282+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:47:51.285+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:47:51.308+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.055 seconds
[2023-05-04T11:48:21.847+0000] {processor.py:153} INFO - Started process (PID=37702) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:48:21.850+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:48:21.852+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:48:21.852+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:48:21.877+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:48:21.874+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:48:21.878+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:48:21.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.058 seconds
[2023-05-04T11:48:52.449+0000] {processor.py:153} INFO - Started process (PID=37716) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:48:52.452+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:48:52.454+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:48:52.453+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:48:52.478+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:48:52.476+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:48:52.479+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:48:52.501+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.057 seconds
[2023-05-04T11:49:23.046+0000] {processor.py:153} INFO - Started process (PID=37730) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:49:23.048+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:49:23.049+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:49:23.049+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:49:23.072+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:49:23.070+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:49:23.073+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:49:23.094+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.053 seconds
[2023-05-04T11:49:53.688+0000] {processor.py:153} INFO - Started process (PID=37744) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:49:53.691+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:49:53.693+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:49:53.693+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:49:53.719+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:49:53.717+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:49:53.720+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:49:53.741+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.059 seconds
[2023-05-04T11:50:24.298+0000] {processor.py:153} INFO - Started process (PID=37758) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:50:24.300+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:50:24.302+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:50:24.302+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:50:24.328+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:50:24.326+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:50:24.329+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:50:24.350+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.057 seconds
[2023-05-04T11:50:54.900+0000] {processor.py:153} INFO - Started process (PID=37772) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:50:54.902+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:50:54.904+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:50:54.904+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:50:54.929+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:50:54.927+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:50:54.930+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:50:54.952+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.059 seconds
[2023-05-04T11:51:25.485+0000] {processor.py:153} INFO - Started process (PID=37786) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:51:25.489+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:51:25.490+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:51:25.490+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:51:25.518+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:51:25.515+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:51:25.519+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:51:25.543+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.064 seconds
[2023-05-04T11:51:56.076+0000] {processor.py:153} INFO - Started process (PID=37800) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:51:56.079+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:51:56.081+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:51:56.081+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:51:56.109+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:51:56.106+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:51:56.111+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:51:56.135+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.065 seconds
[2023-05-04T11:52:26.702+0000] {processor.py:153} INFO - Started process (PID=37831) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:52:26.705+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:52:26.707+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:52:26.707+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:52:26.734+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:52:26.731+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:52:26.735+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:52:26.760+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.063 seconds
[2023-05-04T11:52:57.319+0000] {processor.py:153} INFO - Started process (PID=37853) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:52:57.324+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:52:57.327+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:52:57.326+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:52:57.355+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:52:57.352+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:52:57.357+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:52:57.379+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.064 seconds
[2023-05-04T11:53:27.927+0000] {processor.py:153} INFO - Started process (PID=37867) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:53:27.929+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:53:27.931+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:53:27.931+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:53:27.958+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:53:27.956+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:53:27.960+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:53:27.988+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.067 seconds
[2023-05-04T11:53:58.559+0000] {processor.py:153} INFO - Started process (PID=37881) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:53:58.562+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:53:58.564+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:53:58.564+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:53:58.591+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:53:58.588+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:53:58.593+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:53:58.615+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.062 seconds
[2023-05-04T11:54:29.186+0000] {processor.py:153} INFO - Started process (PID=37895) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:54:29.188+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:54:29.191+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:54:29.191+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:54:29.216+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:54:29.214+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:54:29.217+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:54:29.241+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.061 seconds
[2023-05-04T11:54:59.785+0000] {processor.py:153} INFO - Started process (PID=37909) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:54:59.787+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:54:59.790+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:54:59.790+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:54:59.819+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:54:59.817+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:54:59.822+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:54:59.851+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.071 seconds
[2023-05-04T11:55:30.431+0000] {processor.py:153} INFO - Started process (PID=37923) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:55:30.433+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:55:30.435+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:55:30.435+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:55:30.459+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:55:30.456+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:55:30.461+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:55:30.486+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.059 seconds
[2023-05-04T11:56:01.033+0000] {processor.py:153} INFO - Started process (PID=37937) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:56:01.036+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:56:01.039+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:56:01.039+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:56:01.069+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:56:01.066+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:56:01.071+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:56:01.096+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.069 seconds
[2023-05-04T11:56:31.645+0000] {processor.py:153} INFO - Started process (PID=37958) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:56:31.647+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:56:31.649+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:56:31.649+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:56:31.673+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:56:31.671+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:56:31.674+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:56:31.694+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.055 seconds
[2023-05-04T11:57:02.464+0000] {processor.py:153} INFO - Started process (PID=37977) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:57:02.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:57:02.468+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:57:02.468+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:57:02.494+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:57:02.492+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:57:02.496+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:57:02.522+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.063 seconds
[2023-05-04T11:57:33.212+0000] {processor.py:153} INFO - Started process (PID=37996) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:57:33.214+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:57:33.217+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:57:33.217+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:57:33.245+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:57:33.242+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:57:33.246+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:57:33.273+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.066 seconds
[2023-05-04T11:58:03.915+0000] {processor.py:153} INFO - Started process (PID=38011) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:58:03.918+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:58:03.921+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:58:03.921+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:58:03.955+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:58:03.951+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:58:03.957+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:58:03.984+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.074 seconds
[2023-05-04T11:58:34.643+0000] {processor.py:153} INFO - Started process (PID=38031) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:58:34.647+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:58:34.649+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:58:34.649+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:58:34.677+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:58:34.674+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:58:34.678+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:58:34.703+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.065 seconds
[2023-05-04T11:59:05.386+0000] {processor.py:153} INFO - Started process (PID=38045) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:59:05.388+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:59:05.390+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:59:05.390+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:59:05.417+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:59:05.415+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:59:05.419+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:59:05.443+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.064 seconds
[2023-05-04T11:59:36.353+0000] {processor.py:153} INFO - Started process (PID=38061) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:59:36.357+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T11:59:36.360+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:59:36.359+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:59:36.393+0000] {logging_mixin.py:137} INFO - [2023-05-04T11:59:36.390+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T11:59:36.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T11:59:36.424+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.079 seconds
[2023-05-04T12:00:07.116+0000] {processor.py:153} INFO - Started process (PID=38086) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:00:07.118+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:00:07.121+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:00:07.120+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:00:07.151+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:00:07.148+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:00:07.153+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:00:07.180+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.070 seconds
[2023-05-04T12:00:37.911+0000] {processor.py:153} INFO - Started process (PID=38103) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:00:37.913+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:00:37.916+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:00:37.915+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:00:37.945+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:00:37.942+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:00:37.946+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:00:37.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.066 seconds
[2023-05-04T12:01:08.749+0000] {processor.py:153} INFO - Started process (PID=38119) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:01:08.752+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:01:08.754+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:01:08.754+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:01:08.783+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:01:08.779+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:01:08.784+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:01:08.808+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.065 seconds
[2023-05-04T12:01:39.579+0000] {processor.py:153} INFO - Started process (PID=38134) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:01:39.582+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:01:39.584+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:01:39.583+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:01:39.611+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:01:39.609+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:01:39.613+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:01:39.644+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.070 seconds
[2023-05-04T12:02:10.369+0000] {processor.py:153} INFO - Started process (PID=38155) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:02:10.372+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:02:10.375+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:02:10.374+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:02:10.405+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:02:10.403+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:02:10.407+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:02:10.441+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.079 seconds
[2023-05-04T12:02:41.079+0000] {processor.py:153} INFO - Started process (PID=38171) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:02:41.081+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:02:41.083+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:02:41.083+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:02:41.112+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:02:41.109+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:02:41.113+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:02:41.144+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.071 seconds
[2023-05-04T12:03:11.755+0000] {processor.py:153} INFO - Started process (PID=38185) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:03:11.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:03:11.758+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:03:11.758+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:03:11.785+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:03:11.782+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:03:11.787+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:03:11.807+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.056 seconds
[2023-05-04T12:03:42.378+0000] {processor.py:153} INFO - Started process (PID=38199) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:03:42.380+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:03:42.382+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:03:42.382+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:03:42.407+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:03:42.405+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:03:42.409+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:03:42.432+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.060 seconds
[2023-05-04T12:04:13.003+0000] {processor.py:153} INFO - Started process (PID=38213) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:04:13.005+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:04:13.007+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:04:13.007+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:04:13.032+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:04:13.030+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:04:13.033+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:04:13.056+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.058 seconds
[2023-05-04T12:04:43.709+0000] {processor.py:153} INFO - Started process (PID=38227) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:04:43.711+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:04:43.713+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:04:43.713+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:04:43.739+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:04:43.737+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:04:43.740+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:04:43.761+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.058 seconds
[2023-05-04T12:05:14.340+0000] {processor.py:153} INFO - Started process (PID=38241) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:05:14.343+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:05:14.345+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:05:14.345+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:05:14.372+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:05:14.370+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:05:14.374+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:05:14.397+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.062 seconds
[2023-05-04T12:05:44.995+0000] {processor.py:153} INFO - Started process (PID=38255) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:05:44.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:05:45.000+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:05:45.000+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:05:45.025+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:05:45.023+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:05:45.027+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:05:45.049+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.059 seconds
[2023-05-04T12:06:15.757+0000] {processor.py:153} INFO - Started process (PID=38288) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:06:15.760+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:06:15.762+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:06:15.762+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:06:15.788+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:06:15.785+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:06:15.789+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:06:15.810+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.059 seconds
[2023-05-04T12:06:46.422+0000] {processor.py:153} INFO - Started process (PID=38310) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:06:46.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:06:46.426+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:06:46.426+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:06:46.452+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:06:46.450+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:06:46.454+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:06:46.477+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.061 seconds
[2023-05-04T12:07:17.069+0000] {processor.py:153} INFO - Started process (PID=38324) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:07:17.071+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:07:17.073+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:07:17.073+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:07:17.100+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:07:17.098+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:07:17.101+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:07:17.126+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.062 seconds
[2023-05-04T12:07:47.543+0000] {processor.py:153} INFO - Started process (PID=38338) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:07:47.546+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:07:47.548+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:07:47.548+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:07:47.579+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:07:47.575+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:07:47.581+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:07:47.608+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.073 seconds
[2023-05-04T12:08:18.313+0000] {processor.py:153} INFO - Started process (PID=38352) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:08:18.317+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:08:18.318+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:08:18.318+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:08:18.345+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:08:18.343+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:08:18.347+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:08:18.368+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.059 seconds
[2023-05-04T12:08:48.987+0000] {processor.py:153} INFO - Started process (PID=38374) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:08:48.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:08:48.991+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:08:48.991+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:08:49.016+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:08:49.014+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:08:49.017+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:08:49.042+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.061 seconds
[2023-05-04T12:09:19.553+0000] {processor.py:153} INFO - Started process (PID=38388) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:09:19.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:09:19.558+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:09:19.558+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:09:19.587+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:09:19.584+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:09:19.588+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:09:19.613+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.066 seconds
[2023-05-04T12:09:50.291+0000] {processor.py:153} INFO - Started process (PID=38410) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:09:50.295+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:09:50.298+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:09:50.298+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:09:50.334+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:09:50.330+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:09:50.336+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:09:50.371+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.087 seconds
[2023-05-04T12:10:21.025+0000] {processor.py:153} INFO - Started process (PID=38429) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:10:21.027+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:10:21.028+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:10:21.028+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:10:21.052+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:10:21.050+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:10:21.053+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:10:21.076+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.057 seconds
[2023-05-04T12:10:51.659+0000] {processor.py:153} INFO - Started process (PID=38443) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:10:51.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:10:51.664+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:10:51.663+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:10:51.689+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:10:51.687+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:10:51.690+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:10:51.711+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.057 seconds
[2023-05-04T12:11:22.297+0000] {processor.py:153} INFO - Started process (PID=38457) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:11:22.299+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:11:22.301+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:11:22.301+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:11:22.326+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:11:22.323+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:11:22.328+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:11:22.353+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.062 seconds
[2023-05-04T12:11:52.925+0000] {processor.py:153} INFO - Started process (PID=38472) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:11:52.928+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:11:52.930+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:11:52.930+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:11:52.958+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:11:52.955+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:11:52.959+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:11:52.981+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.062 seconds
[2023-05-04T12:12:23.615+0000] {processor.py:153} INFO - Started process (PID=38486) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:12:23.618+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:12:23.620+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:12:23.620+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:12:23.646+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:12:23.643+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:12:23.648+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:12:23.671+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.062 seconds
[2023-05-04T12:12:54.288+0000] {processor.py:153} INFO - Started process (PID=38503) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:12:54.291+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:12:54.293+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:12:54.293+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:12:54.320+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:12:54.317+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:12:54.322+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:12:54.348+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.065 seconds
[2023-05-04T12:13:25.054+0000] {processor.py:153} INFO - Started process (PID=38518) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:13:25.058+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:13:25.061+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:13:25.061+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:13:25.097+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:13:25.094+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:13:25.099+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:13:25.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.088 seconds
[2023-05-04T12:13:55.780+0000] {processor.py:153} INFO - Started process (PID=38532) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:13:55.782+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:13:55.784+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:13:55.784+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:13:55.809+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:13:55.807+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:13:55.810+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:13:55.832+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.057 seconds
[2023-05-04T12:14:26.394+0000] {processor.py:153} INFO - Started process (PID=38547) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:14:26.396+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:14:26.399+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:14:26.398+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:14:26.427+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:14:26.424+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:14:26.429+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:14:26.457+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.068 seconds
[2023-05-04T12:14:57.019+0000] {processor.py:153} INFO - Started process (PID=38561) to work on /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:14:57.022+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/SubDagExample.py for tasks to queue
[2023-05-04T12:14:57.024+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:14:57.024+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:14:57.051+0000] {logging_mixin.py:137} INFO - [2023-05-04T12:14:57.049+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/SubDagExample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/SubDagExample.py", line 11, in <module>
    'discovery_report_regular': 'discovery_report_regular'
TypeError: 'type' object is not subscriptable
[2023-05-04T12:14:57.053+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/SubDagExample.py
[2023-05-04T12:14:57.078+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/SubDagExample.py took 0.066 seconds
